#FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim
FROM python:3.9

RUN mkdir /code

WORKDIR /code
 
COPY ./requirements.txt /code/requirements.txt 

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
#CMD ["pwd"]
