"""Added tables

Revision ID: c2056bb3ca62
Revises: 13d25fcc31f9
Create Date: 2023-02-17 17:33:37.511001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2056bb3ca62'
down_revision = '13d25fcc31f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_table',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('goal_level', sa.String(length=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('user_level_table',
    sa.Column('user_level_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('user_level_id')
    )
    op.create_table('user_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_level_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('native_language', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal_table.goal_id'], ),
    sa.ForeignKeyConstraint(['user_level_id'], ['user_level_table.user_level_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('book_table',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('book_author', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('word_table',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('word_level', sa.String(length=2), nullable=False),
    sa.Column('uk_word', sa.String(), nullable=False),
    sa.Column('en_word', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_table.book_id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_table')
    op.drop_table('book_table')
    op.drop_table('user_table')
    op.drop_table('user_level_table')
    op.drop_table('goal_table')
    # ### end Alembic commands ###
