version: "3.1"

services:
  backend:
    build: ./backend
    ports:
      - "8008:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST = 127.0.0.1
      - DB_PORT = 3307
      - DB_NAME = dual_edu
      - DB_USER = user
      - DB_PASS = 1qazxsw2
    command: alembic upgrade head
    depends_on:
      - db
    
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: dual_edu
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1qazxsw2'
      MYSQL_HOSTNAME: '127.0.0.1'
      MYSQL_ROOT_PASSWORD: '2wsxcde3'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  web:
    build: ./frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - backend

volumes:
  db-data: