"""Changed collation of es_word

Revision ID: 5a81f27d7e7a
Revises: eff6d8e90d72
Create Date: 2023-04-23 21:04:03.913578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a81f27d7e7a'
down_revision = 'eff6d8e90d72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_ibfk_1', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_word_ibfk_2', 'user_word', type_='foreignkey')
    op.drop_constraint('user_word_ibfk_1', 'user_word', type_='foreignkey')
    op.create_foreign_key(None, 'user_word', 'db_word', ['en_word'], ['en_word'])
    op.create_foreign_key(None, 'user_word', 'book', ['book_id'], ['book_id'])
    op.alter_column('db_word', 'es_word', type_=sa.String(90, collation='utf8mb4_spanish_ci'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_word', type_='foreignkey')
    op.drop_constraint(None, 'user_word', type_='foreignkey')
    op.create_foreign_key('user_word_ibfk_1', 'user_word', 'book', ['book_id'], ['book_id'], ondelete='CASCADE')
    op.create_foreign_key('user_word_ibfk_2', 'user_word', 'db_word', ['en_word'], ['en_word'], ondelete='CASCADE')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_ibfk_1', 'book', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
