"""Changed user_id to id

Revision ID: c3e098006b6d
Revises: eff6d8e90d72
Create Date: 2023-04-10 21:57:14.282039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e098006b6d'
down_revision = 'eff6d8e90d72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_ibfk_1', 'book', type_='foreignkey')
    op.drop_constraint('user_word_ibfk_1', 'user_word', type_='foreignkey')
    op.drop_constraint('user_word_ibfk_2', 'user_word', type_='foreignkey')
    op.alter_column("user",
                     column_name = 'user_id',
                     new_column_name = 'id',
                     existing_type = sa.Integer,
                     existing_nullable = False,
                    )
    op.create_foreign_key(
        'book_ibft_1',
        'book',
        'user',
        ['user_id'],
        ['id']
    )
    op.create_foreign_key(
        'user_word_ibfk_1',
        'user_word',
        'book',
        ['book_id'],
        ['book_id']
    )
    op.create_foreign_key(
        'user_word_ibfk_2',
        'user_word',
        'db_word',
        ['en_word'],
        ['en_word']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
