"""Creating tables

Revision ID: ca837c51814a
Revises: 
Create Date: 2023-03-07 09:52:37.858635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca837c51814a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_word_table',
    sa.Column('en_word', sa.String(length=50), nullable=False),
    sa.Column('word_level', sa.String(length=2), nullable=False),
    sa.Column('uk_word', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('en_word')
    )
    op.create_table('user_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_num_level', sa.Integer(), nullable=False),
    sa.Column('goal_level', sa.String(length=2), nullable=False),
    sa.Column('user_level', sa.String(length=3), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('native_language', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('frame_path', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('book_table',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=50), nullable=False),
    sa.Column('book_author', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('user_word_table',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('en_word', sa.String(length=50), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_table.book_id'], ),
    sa.ForeignKeyConstraint(['en_word'], ['db_word_table.en_word'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_word_table')
    op.drop_table('book_table')
    op.drop_table('user_table')
    op.drop_table('db_word_table')
    # ### end Alembic commands ###
