"""Changed current_num_level to experience

Revision ID: ebf33842024c
Revises: 5a81f27d7e7a
Create Date: 2023-04-25 09:02:08.213579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf33842024c'
down_revision = '5a81f27d7e7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user",
                     column_name = 'current_num_level',
                     new_column_name = 'experience',
                     existing_type = sa.Integer,
                     existing_nullable = False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user",
                     column_name = 'experience',
                     new_column_name = 'current_num_level',
                     existing_type = sa.Integer,
                     existing_nullable = False)
    # ### end Alembic commands ###
